### ISSUE TITLE
没看懂 Rxbus 怎么用的

### ISSUE THREAD

**Issue by tianshaokai** [wangjiegulu/RxAndroidEventsSample#1]
你好 有没有Rxbus 的 文档 啊，想看看Rxbus 怎么用 的，看你的项目看蒙了，

**Comment by wangjiegulu** [comment]
RxBus只是RxJava的一个应用，所以没写文档，具体可以参考下我写的博客：http://www.cnblogs.com/tiantianbyconan/p/4578699.html

**Comment by bigthouzand** [comment]
为什么要subjectMapper来存多个subject？[https://github.com/kaushikgopal/RxJava-Android-Samples](https://github.com/kaushikgopal/RxJava-Android-Samples) 这个demo中好像只有一个subject。初学，多指教

**Comment by zhangyuwan0** [comment]
@HaagenDaz 作者这块是像把事件弄成队列吧  毕竟eventBus也是这么实现的

**Comment by renjinlong** [comment]
解析注解的方法  没怎么看懂？例如如何解析出activity里的@Accept 。
我只知道@parserMethodAnnotations可以解析@Accept   但是如何到@parserMethodAnnotations这一步的呢？

**Comment by gzfgeh** [comment]
有注解的RxBus感觉太复杂了，要添加好多东西，Application，BaseActivity，自己的Event，没有不加注解的简单易懂，你们怎么看

**Comment by renjinlong** [comment]
@Accept 
又出现问题了     混淆的时候如果使用注解会出现问题   但是不使用混淆就不会出现问题

难道是我混淆的把注解不混淆这一部分代码写错了

**Comment by gzfgeh** [comment]
QQ群：158943444 有时间大家讨论下

**Comment by zhangyuwan0** [comment]
有兴趣可以看下我改的,只需要Rxjava这个库就可以

------------------ 原始邮件 ------------------
发件人: "福临天下";notifications@github.com;
发送时间: 2016年4月27日(星期三) 下午5:16
收件人: "wangjiegulu/RxAndroidEventsSample"RxAndroidEventsSample@noreply.github.com; 
抄送: "帅气的小楽"944804675@qq.com; "Comment"comment@noreply.github.com; 
主题: Re: [wangjiegulu/RxAndroidEventsSample] 没看懂 Rxbus 怎么用的 (#1)

有注解的RxBus感觉太复杂了，要添加好多东西，Application，BaseActivity，自己的Event，没有不加注解的简单易懂，你们怎么看

**Comment by gzfgeh** [comment]
@zhangyuwan0  地址呢？

**Comment by zhangyuwan0** [comment]
你联系我QQ吧 944804675

------------------ 原始邮件 ------------------
发件人: "福临天下";notifications@github.com;
发送时间: 2016年4月28日(星期四) 上午9:05
收件人: "wangjiegulu/RxAndroidEventsSample"RxAndroidEventsSample@noreply.github.com; 
抄送: "帅气的小楽"944804675@qq.com; "Mention"mention@noreply.github.com; 
主题: Re: [wangjiegulu/RxAndroidEventsSample] 没看懂 Rxbus 怎么用的 (#1)

@zhangyuwan0  地址呢？

**Comment by wangjiegulu** [comment]
@renjinlong 需要添加的混淆如下：

```
# ======================= RxBus annotation START ================
-keep class [package of @Accept].accept.** {*;}
-keepclasseswithmembers class * {
  @[package of @Accept].Accept <methods>;
}
# ======================= RxBus annotation END ================
```

**Comment by wangjiegulu** [comment]
@renjinlong parserMethodAnnotations的具体实现可以查看[AndroidInject](https://github.com/wangjiegulu/androidInject)源码：[RealizeMethodAnnotation](https://github.com/wangjiegulu/androidInject/blob/master/src%2Fcom%2Fwangjie%2Fandroidinject%2Fannotation%2Fcore%2Fbase%2FRealizeMethodAnnotation.java)
