### ISSUE TITLE
我有一个Activity在BaseActivity里面继承了，怎么办？

### ISSUE THREAD

**Issue by gzfgeh** [wangjiegulu/RxAndroidEventsSample#3]
没办法继承AIAppCompatActivity 这个，如何解决

**Comment by wangjiegulu** [comment]
可以修改你的`BaseActivity`实现`AIPresent`和`CallbackSample`两个接口，这两个接口的具体实现可以参考[AIAppCompatActivity](https://github.com/wangjiegulu/androidInject/blob/master/src%2Fcom%2Fwangjie%2Fandroidinject%2Fannotation%2Fpresent%2FAIAppCompatActivity.java)的实现方式，与它的实现一摸一样即可
